---
- hosts: all
  vars:
    db_user: userapp
    db_password: password
    app_database_name: user_app
    host_user: "{{ lookup('env','USER') }}"
    project_root: "~/project"
    project_path: "{{ project_root }}"
    redis_port: 6379
    redis_password: secret
    rabbitmq_username: user2
    rabbitmq_password: secret
    mail_message_queue: mail.message.queue
    sdkman_script_install_url: http://get.sdkman.io
    sdkman_folder: "~/.sdkman"
  tasks:
    - name: make sure the system encoding is utf-8
      become: yes
      template:
        src: templates/locale
        dest: /etc/default/locale
        owner: root
        group: root
        mode: 0644

    - include: tasks/apt.yml
    - include: tasks/oh-my-zshell.yml
    - include: tasks/mailcatcher.yml
    - include: tasks/java.yml
    - include: tasks/postgresql.yml
    - include: tasks/redis.yml
    - include: tasks/rabbitmq.yml
    - include: tasks/finetune.yml
    - include: tasks/application.yml