---
  - name: Installing mailcatcher
    become: yes
    shell: gem install mailcatcher --no-ri --no-rdoc
    args:
      chdir: "~"
      executable: /bin/zsh

  - name: start mailcatcher
    shell: mailcatcher --ip 0.0.0.0
    ignore_errors: yes