---
  - name: Installing mailcatcher
    become: yes
    shell: gem install mailcatcher --no-ri --no-rdoc
    args:
      chdir: "{{ user_home_path }}"
      executable: /bin/zsh

  - name: start mailcatcher
    shell: mailcatcher --ip 0.0.0.0